import assert from 'node:assert/strict';
import { readFileSync, existsSync, unlinkSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

// Clean up any previous output to ensure the sync script actually creates the files
['skills/brainstorming/scripts/frame-template.html',
 'templates/spec.template.html',
 'templates/plan.template.html'
].forEach((f) => {
  try { unlinkSync(f); } catch (_) { /* ok */ }
});

const run = spawnSync('node', ['scripts/sync-html-templates.mjs'], { encoding: 'utf8' });
assert.equal(run.status, 0, run.stderr);

assert(existsSync('skills/brainstorming/scripts/frame-template.html'));
assert(existsSync('templates/spec.template.html'));
assert(existsSync('templates/plan.template.html'));

// Each generated template must contain the banner comment
const specHtml = readFileSync('templates/spec.template.html', 'utf8');
assert(specHtml.includes('Generated by scripts/sync-html-templates.mjs'));

const planHtml = readFileSync('templates/plan.template.html', 'utf8');
assert(planHtml.includes('Generated by scripts/sync-html-templates.mjs'));

const brainstormHtml = readFileSync('skills/brainstorming/scripts/frame-template.html', 'utf8');
assert(brainstormHtml.includes('Generated by scripts/sync-html-templates.mjs'));

// Verify placeholder markers exist in output (brainstorm uses <!-- CONTENT --> for server compat)
assert(brainstormHtml.includes('<!-- CONTENT -->'));
assert(specHtml.includes('{{CONTENT}}'));
assert(planHtml.includes('{{CONTENT}}'));
assert(specHtml.includes('{{DOC_TITLE}}'));
assert(planHtml.includes('{{DOC_TITLE}}'));

// Verify self-contained: no external stylesheet or script refs
assert(!specHtml.includes('<link rel="stylesheet"'));
assert(!planHtml.includes('<link rel="stylesheet"'));
assert(!brainstormHtml.includes('<link rel="stylesheet"'));
assert(!specHtml.includes('<script src='));
assert(!planHtml.includes('<script src='));
assert(!brainstormHtml.includes('<script src='));

// Verify template-kind attributes
assert(brainstormHtml.includes('data-template-kind="brainstorm"'));
assert(specHtml.includes('data-template-kind="spec"'));
assert(planHtml.includes('data-template-kind="plan"'));

console.log('All template-sync tests passed.');
