import assert from 'node:assert/strict';
import { readFileSync, existsSync, unlinkSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

// Clean up any previous output to ensure the sync script actually creates the files
['skills/brainstorming/scripts/frame-template.html',
 'templates/spec.template.html',
 'templates/plan.template.html'
].forEach((f) => {
  try { unlinkSync(f); } catch (_) { /* ok */ }
});

const run = spawnSync('node', ['scripts/sync-html-templates.mjs'], { encoding: 'utf8' });
assert.equal(run.status, 0, run.stderr);

assert(existsSync('skills/brainstorming/scripts/frame-template.html'));
assert(existsSync('templates/spec.template.html'));
assert(existsSync('templates/plan.template.html'));

// Each generated template must contain the banner comment
const specHtml = readFileSync('templates/spec.template.html', 'utf8');
assert(specHtml.includes('Generated by scripts/sync-html-templates.mjs'));

const planHtml = readFileSync('templates/plan.template.html', 'utf8');
assert(planHtml.includes('Generated by scripts/sync-html-templates.mjs'));

const brainstormHtml = readFileSync('skills/brainstorming/scripts/frame-template.html', 'utf8');
assert(brainstormHtml.includes('Generated by scripts/sync-html-templates.mjs'));

// Verify placeholder markers exist in output (brainstorm uses <!-- CONTENT --> for server compat)
assert(brainstormHtml.includes('<!-- CONTENT -->'));
assert(brainstormHtml.includes('claude-content'), 'Should have claude-content container for server compat');

// Verify brainstorm frame compatibility: key hooks the server and helper.js rely on
assert(brainstormHtml.includes('indicator-bar'), 'Should have indicator-bar');
assert(brainstormHtml.includes('indicator-text'), 'Should have indicator-text');
assert(brainstormHtml.includes('Connected'), 'Should have Connected status');

// Spec uses structured placeholders (not plain {{CONTENT}})
assert(!specHtml.includes('{{CONTENT}}'), 'Spec should not use plain {{CONTENT}}');
assert(specHtml.includes('{{TOC_ITEMS}}'));
assert(specHtml.includes('{{OVERVIEW}}'));
assert(specHtml.includes('{{DOC_TITLE}}'));

assert(planHtml.includes('{{CONTENT}}'));
assert(planHtml.includes('{{DOC_TITLE}}'));

// Verify self-contained: no external stylesheet or script refs
assert(!specHtml.includes('<link rel="stylesheet"'));
assert(!planHtml.includes('<link rel="stylesheet"'));
assert(!brainstormHtml.includes('<link rel="stylesheet"'));
assert(!specHtml.includes('<script src='));
assert(!planHtml.includes('<script src='));
assert(!brainstormHtml.includes('<script src='));

// Verify template-kind attributes
assert(brainstormHtml.includes('data-template-kind="brainstorm"'));
assert(specHtml.includes('data-template-kind="spec"'));
assert(planHtml.includes('data-template-kind="plan"'));

// Phase 2: spec-shell assertions
assert(specHtml.includes('data-doc-kind="spec"'));
assert(specHtml.includes('class="sp-toc"'));
assert(specHtml.includes('theme-toggle'));
assert(specHtml.includes('localStorage'));
assert(specHtml.includes('id="overview"'));

console.log('All template-sync tests passed.');
